site_name: Producción Electrónica.
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
# Use the ReadTheDocs theme
theme:
  name: material
  highlightjs: true
  icon:
    logo: material/chip
  palette:
      - scheme: slate
        primary: indigo
        accent: cyan
  features:
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - toc.integrate
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
  - recursos/archivos/custom.css

nav:
  - Portafolio de documentación: index.md
  - Equipo de Trabajo: Equipo de trabajo.md
  - Guía de Inicio Rápido con KiCad: Primeros pasos Kicad.md
  - Procesamiento de SVG a RML: Mods CE.md
